%YAML 1.2
---
source: "network"

scheduler:
  worker_thread_number: 5
  stop_on_deadlock: true
  stop_on_deadlock_timeout: 500
  check_recession_period_ms: 0
  #worker_thread_priority: 99
  # Pin worker threads to specific cores to avoid contention with DPDK (core 9) and master (core 1)
  # Adjust these core IDs based on your system topology (e.g., NUMA node 0)
  #worker_thread_affinity: [2, 3, 4, 5, 6]

advanced_network:
  cfg:
    version: 1
    manager: "dpdk"
    master_core: 3
    debug: false
    log_level: "info"
    
    memory_regions:
    - name: "Data_RX_GPU_0"
      kind: "device"
      affinity: 0
      num_bufs: 262144
      buf_size: 9228 
    - name: "Data_RX_GPU_1"
      kind: "device"
      affinity: 0
      num_bufs: 262144
      buf_size: 9228
      
    interfaces:
    - name: "rx_port_0"
      address: "0005:03:00.0"
      rx:
        flow_isolation: true
        queues:
        - name: "rx_q_0"
          id: 0
          cpu_core: 9
          batch_size: 16384
          memory_regions:
            - "Data_RX_GPU_0"
        flows:
        - name: "flow_0"
          id: 0
          action:
            type: queue
            id: 0
          match:
            udp_dst: 23130
    - name: "rx_port_1"
      address: "0005:03:00.1"
      rx:
        flow_isolation: true
        queues:
        - name: "rx_q_1"
          id: 0
          cpu_core: 10
          batch_size: 16384
          memory_regions:
            - "Data_RX_GPU_1"
        flows:
        - name: "flow_1"
          id: 0
          action:
            type: queue
            id: 0
          match:
            udp_dst: 23130
            
receiver0:
  interface_name: "rx_port_0"
  frames_per_tensor: 128
  max_packet_size: 9100
  header_size: 42
  gpu_direct: true
  split_boundary: false
  reorder_kernel: true
  count: 100000 # Process some number of frames then stop
  # packet_debug: true
  # packet_debug_output_prefix: "/workspace/holohub/build/stem_networking_bench/applications/stem_networking_bench/cpp/recv0_packet_debug"
  # packet_debug_max_batches: 2

receiver1:
  interface_name: "rx_port_1"
  frames_per_tensor: 128
  max_packet_size: 9100
  header_size: 42
  gpu_direct: true
  split_boundary: false
  reorder_kernel: true
  count: 100000 # Process some number of frames then stop
  # packet_debug: true
  # packet_debug_output_prefix: "/workspace/holohub/build/stem_networking_bench/applications/stem_networking_bench/cpp/recv1_packet_debug"
  # packet_debug_max_batches: 2

processor:
  noop: true
  # Add any parameters for your processor op here

writer:
  filepath: "/home/daquser/jrenner/sparse_frames_out_net.h5"
  dataset_name: "/processed"
  noop: true

    #resources:
  #  - &allocator
  #  type: holoscan::UnboundedAllocator
  #  name: "pool"
