/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/eels/detector/rows 64
/eels/detector/columns 128
/eels/detector/pixelPitch 10 um
/eels/detector/thickness 5 um
/eels/detector/maxStep 0.1 um
/run/initialize
/random/setSeeds 270353837 20597151
/eels/source/energy 300 keV
/eels/source/energySigma 0 keV
/eels/source/sigmaX 2 um
/eels/source/sigmaY 2 um
/eels/source/angularSigma 0 mrad
/eels/source/z -5 um
/eels/output/file output/calibration_300keV
/run/printProgress 200
/run/beamOn 1000
